version: '3'
services:
  web:
    image: e-navigator
    volumes:
      - .:/app
      - share:/usr/local/bundle
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: scripts/start-server.sh

volumes:
  share:

