version: '3'
services:
  web:
    image: e-navigator
    volumes:
      - .:/app
      - share:/usr/local/bundle
    ports:
      - 3000:3000
    command: scripts/start-server.sh
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  share:
  db_data:
